### ISSUE TITLE
Translation for locale with country code (pt_BR) is from the language without country code (pt)

### ISSUE THREAD

**Issue by velsinki** [ximion/appstream#680]
Over at GNOME Settings, someone reported https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/3252. I traced this back to what is most likely an AppStream issue.

Basically, we have an appdata.xml file ([org.gnome.Settings.appdata.xml.zip](https://github.com/user-attachments/files/17688628/org.gnome.Settings.appdata.xml.zip)) that has

```xml
  <name xml:lang="pt_BR">Configurações</name>
  <name xml:lang="pt">Definições</name>
```

But if I

```bash
LANG=pt_BR.UTF-8 appstreamcli dump org.gnome.Settings.desktop
```

I get

```xml
  <name>Definições</name>
```

instead. The description and developer name are also from `pt` instead of `pt_BR`. That doesn't seem correct to me.

Is there anything we are doing wrong, or is this an issue from here?

**Comment by ximion** [comment]
Yes! The `xml:lang` attribute is in the wrong format, it needs to be a BCP47 locale as specified by the XML spec, no POSIX locale. I guess all you need to do is either use [itstool](https://mesonbuild.com/i18n-module.html#i18nitstool_join) for creating the final XML, or update xgettext because this issue should have been fixed in recent versions of Gettext :-)

**Comment by ximion** [comment]
Yes! The `xml:lang` attribute is in the wrong format, it needs to be a BCP47 locale as specified by the XML spec, no POSIX locale. I guess all you need to do is either use [itstool](https://mesonbuild.com/i18n-module.html#i18nitstool_join) for creating the final XML, or update xgettext because this issue should have been fixed in recent versions of Gettext :-)

Let me know if this works for you!

**Comment by ximion** [comment]
Excellent, looks like you are either using itstool or a more recent version of xgettext now :-)

**Comment by rffontenelle** [comment]
@ximion do you happen to know the version of gettext or itstool where this was fixed?

Although this is fixed for the software built in Arch Linux (which provides updated gettext), hundreds of flathub's and gnome-nightly's apps still have the incorrect language tag, so I'm trying to narrow down versions to help me solve this with the proper infrastructure team.
